name: Keep Backend Alive

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  ping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        id: ping
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            https://gallo-api.onrender.com/api/v1)

          echo "Response: $RESPONSE"

          if [ "$RESPONSE" -ne 200 ]; then
            echo "service_down=true" >> $GITHUB_ENV
          else
            echo "service_down=false" >> $GITHUB_ENV
          fi
